version: "3.9"
services:
    gateway:
        hostname: shop_example_gateway
        container_name: shop_example_gateway
        build:
            context: .
            dockerfile: GatewayDockerfile
        ports:
            - "5000:80"
    catalog:
        hostname: shop_example_catalog
        container_name: shop_example_catalog
        build:
            context: .
            dockerfile: CatalogDockerfile
        ports:
            - "5001:80"
    basket:
        hostname: shop_example_basket
        container_name: shop_example_basket
        build:
            context: .
            dockerfile: BasketDockerfile
        ports:
            - "5002:80"
    user:
        hostname: shop_example_user
        container_name: shop_example_user
        build:
            context: .
            dockerfile: UserDockerfile
        ports:
            - "5003:80"
    postgres:
        image: postgres
        container_name: shop_example_postgres
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "12345"
        ports:
            - "5432:5432"
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: shop_example_rabbit
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "123"
            RABBITMQ_DEFAULT_VHOST: "shop"
